# Generated by Django 4.2.13 on 2024-06-24 21:11

from django.db import migrations


def assign_blog_permissions(apps, schema_migration):
    """The function who will assign the blog permissions"""

    # Retrieve models using the apps.get_model() function
    # we cannot access models directly from imports, use the apps.get_model() function to retrieve them
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Get permissions for Blog model
    add_blog = Permission.objects.get(codename='add_blog')
    change_blog = Permission.objects.get(codename='change_blog')
    delete_blog = Permission.objects.get(codename='delete_blog')
    view_blog = Permission.objects.get(codename='view_blog')

    creator_permissions = [add_blog, change_blog, delete_blog, view_blog]

    # Get creators groups
    creators = Group.objects.get(name='creators')
    # Assign permissions to the creators groups
    creators.permissions.set(creator_permissions)

    # Get subscribers groups
    subscribers = Group.objects.get(name='subscribers')
    # Assign permissions to the subscribers groups
    subscribers.permissions.add(view_blog)


class Migration(migrations.Migration):
    # list the migrations that must be executed before this one
    dependencies = [
        ("authentication", "0003_auto_20240624_1842"),
    ]

    # list of operations that the migration will perform
    operations = [
        # add the assign_blog_permissions function as an argument to the migrations.RunPython class
        migrations.RunPython(assign_blog_permissions)
    ]
