# Generated by Django 4.2.13 on 2024-06-25 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_auto_20240624_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                limit_choices_to={"role": "CREATOR"}, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
