# Generated by Django 4.2.13 on 2024-06-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="word_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
