# Generated by Django 4.2.13 on 2024-06-25 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_word_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("change_blog_title", "Can change the title of a blog post")
                ]
            },
        ),
    ]
