# Generated by Django 4.2.13 on 2024-06-26 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_migrate_author_to_contributors"),
    ]

    operations = [
        # # remove the author field from Blog after migration in this one
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
    ]
